'use client';
import {useEffect,useMemo,useState} from 'react';
type Service={id:string;name:string;note:string;price:number;time:string;tag:string;icon:string;active:boolean;image:string};
const defaultServices:Service[]=[{id:'feather',name:'无痕羽毛接发',note:'轻盈自然 · 可扎高马尾',price:1280,time:'约 3 小时',tag:'人气首选',icon:'〽',active:true,image:''},{id:'nano6d',name:'6D 纳米接发',note:'隐形牢固 · 适合细软发',price:1580,time:'约 3.5 小时',tag:'自然隐形',icon:'◌',active:true,image:''},{id:'care',name:'接发拆卸护理',note:'专业拆卸 · 深层修护',price:299,time:'约 1.5 小时',tag:'养护必选',icon:'✦',active:true,image:''}];
const normalizeServices=(value:unknown):Service[]=>Array.isArray(value)?value.map((raw,index)=>{const item=raw as any;return Array.isArray(item)?{id:String(item[4]||`product-${index}`),name:String(item[0]||'未命名商品'),note:String(item[1]||''),price:Number(item[2])||0,time:String(item[3]||'约 3 小时'),tag:['人气首选','自然隐形','养护必选','后台同步'][index%4],icon:['〽','◌','✦','雅'][index%4],active:item[5]!==false,image:String(item[6]||'')}:{id:String(item?.id||`product-${index}`),name:String(item?.name||'未命名商品'),note:String(item?.note||item?.desc||''),price:Number(item?.price)||0,time:String(item?.time||item?.duration||'约 3 小时'),tag:String(item?.tag||'后台同步'),icon:String(item?.icon||item?.mark||'雅'),active:item?.active!==false,image:String(item?.image||'')}}).filter(item=>item.name&&item.price>0&&item.active!==false):[];
const stores=[{name:'温州鹿城店',address:'温州市鹿城区城市中心商圈'},{name:'温州鳌江店',address:'温州市平阳县鳌江镇中心商圈'},{name:'温州苍南店',address:'温州市苍南县灵溪镇中心商圈'}];
const days=[{week:'周一',date:'24'},{week:'周二',date:'25'},{week:'周三',date:'26'},{week:'周四',date:'27'},{week:'周五',date:'28'},{week:'周六',date:'29'},{week:'周日',date:'30'}],times=['12:00','14:00','16:00','18:00','20:00','22:00','24:00'];
type CirclePost={name:string;avatar:string;tag:string;text:string;meta:string;likes:number;ownerId:string;image?:string};
const currentUserId='user-qingsi-001';
export default function Home(){const[services,setServices]=useState<Service[]>(defaultServices),[step,setStep]=useState<'home'|'booking'|'success'|'profile'|'community'>('home'),[service,setService]=useState(0),[store,setStore]=useState(0),[day,setDay]=useState(0),[time,setTime]=useState('14:00'),[showContact,setShowContact]=useState(false),[message,setMessage]=useState(''),[postImage,setPostImage]=useState(''),[posts,setPosts]=useState<CirclePost[]>([{name:'鹿鹿',avatar:'鹿',tag:'接发体验',text:'第一次做羽毛接发，睡觉会不会硌头呀？有经验的姐妹聊聊～',meta:'鹿城店 · 12分钟前',likes:18,ownerId:'user-lulu'},{name:'小满',avatar:'满',tag:'养护分享',text:'接发后一周实测：洗头前先把发尾梳顺，吹头发时从接点向下吹，真的不容易打结。',meta:'苍南店 · 36分钟前',likes:42,ownerId:'user-xiaoman'},{name:'阿青',avatar:'青',tag:'门店交流',text:'想约鳌江店，细软发更推荐羽毛接发还是6D纳米？',meta:'鳌江店 · 1小时前',likes:9,ownerId:'user-aqing'}]);useEffect(()=>{const load=()=>{try{const stored=localStorage.getItem('lengtheProducts')||localStorage.getItem('lengtheProductsBackup'),next=stored?normalizeServices(JSON.parse(stored)):[];if(next.length){setServices(next);setService(current=>Math.min(current,next.length-1))}}catch{}};load();window.addEventListener('storage',load);return()=>window.removeEventListener('storage',load)},[]);const selected=useMemo(()=>services[service]||services[0]||defaultServices[0],[service,services]);const publish=()=>{if(!message.trim()&&!postImage)return;setPosts([{name:'青丝会员',avatar:'我',tag:'新话题',text:message.trim()||'分享了一张接发照片',meta:'刚刚发布',likes:0,ownerId:currentUserId,image:postImage||undefined},...posts]);setMessage('');setPostImage('')};const removePost=(index:number)=>{if(posts[index]?.ownerId!==currentUserId)return;setPosts(posts.filter((_,postIndex)=>postIndex!==index))};const chooseImage=(file?:File)=>{if(!file)return;const reader=new FileReader();reader.onload=()=>setPostImage(String(reader.result));reader.readAsDataURL(file)};return <main className="app-shell"><div className="phone">
<header className="topbar"><div className="brand" onClick={()=>setStep('home')}><span>LE</span><b>LENGTHÉ</b></div><button className="contact-entry" aria-label="联系客服" onClick={()=>setShowContact(true)}>联系客服</button></header>
{step==='home'&&<><section className="hero"><div className="seal">髮</div><div className="hero-copy"><p className="eyebrow">东方发艺 · 自然新生</p><h1>一缕青丝<br/>一境东方</h1><p className="subcopy">以东方审美重塑发丝韵律<br/>定制你的理想长度与发量</p><button className="primary" onClick={()=>setStep('booking')}>立即预约 <span>→</span></button></div><div className="hair-art" aria-hidden="true"><i/><i/><i/><i/><div className="model-head"/></div></section>
<section className="store-card"><div className="store-photo"><span>三店通约</span></div><div className="store-info"><div><p className="mini-title">温州门店</p><h2>Lengthé 接发美学 · {stores[store].name}</h2><p>{stores[store].address}</p></div><button aria-label="查看门店位置">⌖</button></div><div className="store-meta"><span>◷ 12:00—24:00</span><span>鹿城 · 鳌江 · 苍南</span><span>★ 4.9</span></div></section>
<section className="content-section"><div className="section-heading"><div><p className="eyebrow">SERVICE</p><h2>精选接发项目</h2></div><button>查看全部 →</button></div><div className="services">{services.map((item,index)=><button key={item.name} className="service-item" onClick={()=>{setService(index);setStep('booking')}}><span className={`service-icon ${item.image?'has-photo':''}`}>{item.image?<img src={item.image} alt="商品照片"/>:item.icon}</span><span className="service-main"><b>{item.name}</b><small>{item.note}</small><em>{item.tag}</em></span><span className="service-price"><b>¥{item.price}</b><small>起</small><i>›</i></span></button>)}</div></section>
<section className="promise"><div><span>01</span><b>真发保障</b><small>精选顺滑真人发</small></div><div><span>02</span><b>7天调整</b><small>不满意免费微调</small></div><div><span>03</span><b>专属档案</b><small>记录每次接发方案</small></div></section></>}
{step==='booking'&&<section className="booking-page"><button className="back" onClick={()=>setStep('home')}>←</button><p className="eyebrow">东方发艺 · 到店之约</p><h1>预约到店</h1><p className="booking-intro">三家门店均可预约 · 时段 12:00—24:00</p>
<div className="booking-block"><h3><span>01</span> 选择门店</h3><div className="store-choices">{stores.map((item,index)=><button key={item.name} className={store===index?'active':''} onClick={()=>setStore(index)}><b>{item.name}</b><small>{item.address}</small></button>)}</div></div>
<div className="booking-block"><h3><span>02</span> 选择项目</h3><div className="choice-list">{services.map((item,index)=><button key={item.name} className={service===index?'active':''} onClick={()=>setService(index)}>{item.image&&<img className="choice-photo" src={item.image} alt="商品照片"/>}<span><b>{item.name}</b><small>{item.time}</small></span><strong>¥{item.price}起</strong></button>)}</div></div>
<div className="booking-block"><h3><span>03</span> 选择到店时间</h3><p className="slot-note">周一至周日均可预约 · 每 2 小时一档</p><div className="days">{days.map((item,index)=><button key={item.date} className={day===index?'active':''} onClick={()=>setDay(index)}><small>{item.week}</small><b>{item.date}</b></button>)}</div><div className="times">{times.map(item=><button key={item} className={time===item?'active':''} onClick={()=>setTime(item)}>{item}</button>)}</div></div>
<button className="service-link" onClick={()=>setShowContact(true)}>不确定怎么选？联系在线客服</button>
<div className="booking-footer"><div><small>预约项目</small><b>{selected.name}</b><span>¥{selected.price} 起</span></div><button onClick={()=>setStep('success')}>确认预约</button></div></section>}
{step==='success'&&<section className="success-page"><div className="success-mark">✓</div><p className="eyebrow">BOOKING CONFIRMED</p><h1>预约成功</h1><p>一缕青丝，静候相逢</p><div className="ticket"><div><small>预约项目</small><b>{selected.name}</b></div><div><small>到店时间</small><b>8月{days[day].date}日 {time}</b></div><div><small>预约门店</small><b>Lengthé · {stores[store].name}</b></div></div><button className="primary wide" onClick={()=>setStep('home')}>返回首页</button></section>}
{step==='community'&&<section className="community-page"><div className="community-head"><p className="eyebrow">HAIR CARE CIRCLE</p><h1>青丝交流圈</h1><p>聊接发，也聊每一段变美的心情</p><div className="circle-count"><span><b>2,680</b> 圈友</span><span><b>368</b> 今日交流</span></div></div><div className="topic-tabs"><button className="active">推荐</button><button>养护经验</button><button>接发问答</button><button>门店交流</button></div><div className="daily-topic"><span>今日话题</span><div><b># 接发后怎样洗头更顺滑？</b><small>已有 86 位圈友参与</small></div><i>›</i></div>{postImage&&<div className="image-preview"><img src={postImage} alt="待发布图片预览"/><button onClick={()=>setPostImage('')}>×</button></div>}<div className="post-list">{posts.map((post,index)=><article className="post" key={`${post.name}-${index}`}><header><span>{post.avatar}</span><div><b>{post.name}</b><small>{post.meta}</small></div><em>{post.tag}</em></header><p>{post.text}</p>{post.image&&<img className="post-image" src={post.image} alt="圈友发布的接发图片"/>}<footer><button>♡ {post.likes}</button><button>◯ 聊一聊</button><button>↗ 分享</button>{post.ownerId===currentUserId&&<button className="delete-post" onClick={()=>removePost(index)}>⌫ 删除</button>}</footer></article>)}</div><div className="chat-composer"><label aria-label="添加图片">＋<input type="file" accept="image/*" onChange={event=>chooseImage(event.target.files?.[0])}/></label><input value={message} onChange={event=>setMessage(event.target.value)} onKeyDown={event=>{if(event.key==='Enter')publish()}} placeholder="分享经验，或问问圈友…"/><button onClick={publish}>发布</button></div></section>}
{step==='profile'&&<section className="profile-page"><div className="profile-hero"><div className="profile-orbit"/><div className="avatar">青</div><div><p className="eyebrow">MY LENGTHÉ</p><h1>青丝会员</h1><span>普通会员 · 再消费 ¥720 升级银卡</span></div><button aria-label="个人设置">⚙</button></div><div className="member-progress"><div><span>会员成长值</span><b>280 / 1000</b></div><i><em/></i></div><section className="profile-card"><div className="profile-title"><h2>我的预约</h2><button onClick={()=>setStep('booking')}>全部预约 ›</button></div><div className="appointment-row"><span className="calendar-mark"><small>8月</small><b>{days[day].date}</b></span><div><b>{selected.name}</b><small>{stores[store].name} · {time}</small></div><em>待到店</em></div></section><div className="profile-stats"><button><b>1</b><small>预约</small></button><button><b>2</b><small>优惠券</small></button><button><b>3</b><small>收藏</small></button><button><b>280</b><small>积分</small></button></div><section className="profile-menu"><button onClick={()=>setStep('booking')}><span>约</span><b>立即预约</b><i>›</i></button><button onClick={()=>setShowContact(true)}><span>问</span><b>联系客服</b><i>›</i></button><button><span>店</span><b>我的常用门店</b><small>{stores[store].name}</small><i>›</i></button><button><span>档</span><b>我的接发档案</b><i>›</i></button><button><span>礼</span><b>优惠券与会员权益</b><i>›</i></button></section><p className="profile-foot">一缕青丝 · 一生珍重</p></section>}
{showContact&&<div className="contact-mask" onClick={()=>setShowContact(false)}><section className="contact-card" onClick={event=>event.stopPropagation()}><button className="contact-close" onClick={()=>setShowContact(false)}>×</button><div className="contact-seal">问</div><p className="eyebrow">ONLINE SERVICE</p><h2>联系专属客服</h2><p>项目、发量和门店选择问题，都可以先咨询我们。</p><a href="tel:400-888-1212">拨打客服 400-888-1212</a><button className="wechat-btn">微信客服 · 点击咨询</button><small>在线时间：每日 12:00—24:00</small></section></div>}
<nav className="tabbar" aria-label="底部导航"><button className={step==='home'?'active':''} onClick={()=>setStep('home')}><span>⌂</span>首页</button><button className={step==='booking'?'active':''} onClick={()=>setStep('booking')}><span>◫</span>预约</button><button className={step==='community'?'active':''} onClick={()=>setStep('community')}><span>◎</span>交流圈</button><button className={step==='profile'?'active':''} onClick={()=>setStep('profile')}><span>♙</span>我的</button></nav></div></main>}
